name: Oppgave 16

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10_clean.ps1 -Kortstokk "http://nav-deckofcards.herokuapp.com/shuffle"

      - name: Login via AZ module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPsSession: true